function Hd = highpass
%HIGHPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 20-Jun-2024 23:30:55

% FIR Window Highpass filter designed using the FIR1 function.

% All frequency values are in MHz.
Fs = 125;  % Sampling Frequency

N    = 30;       % Order
Fc   = 1.35;     % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'high', win, flag);
Hd = dfilt.dffir(b);

[h,w] = freqz(Hd);



writematrix(angle(h) * 180 / pi, "highpass_hphase.txt")


% [EOF]
